Repository EPPlusSoftware/EPPlus, pull requests merged in 2024-11, with the labels that each got.

#1672 Fixes issue #1671
  src/EPPlus/FormulaParsing/DependencyChain/RpnFormulaExecution.cs
  src/EPPlusTest/Issues/FormulaCalculationIssues.cs
Labels: bug

#1661 Feature/copyfill
  src/EPPlus/Core/RangeCopyHelper.cs
  src/EPPlus/ExcelCellBase.cs
  src/EPPlus/ExcelRange.cs
  src/EPPlus/ExcelRangeBase.cs
  src/EPPlus/ExcelRangeCopyOptionFlags.cs
  src/EPPlusTest/Core/Range/RangeAddressCopyTests.cs
  src/EPPlusTest/ExcelRangeBaseTests.cs
Labels: enhancement

#1676 #1674 - Fix for cells with null values and no styleid getting incorrect styling
  src/EPPlus/Core/Worksheet/XmlWriter/WorksheetXmlWriter.cs
  src/EPPlus/ExcelWorksheet.cs
Labels: bug

#1679 -Set ApplyFiltersOnSave default value to false
  docs/articles/breakingchanges.md
  src/EPPlus/ExcelPackageSettings.cs
  src/EPPlus/ExcelRangeColumn.cs
  src/EPPlus/ExcelRow.cs
  src/EPPlus/Filter/ExcelAutoFilter.cs
Labels: bug, enhancement

#1684 Feature/override borders
  docs/articles/fixedissues.md
  src/EPPlus/Style/ExcelBorder.cs
  src/EPPlusTest/Style/StylingTest.cs
Labels: enhancement
